### PR TITLE
fix: Remove hardcoded token claim

### PR DESCRIPTION
**Pull request by manusa**
I haven't tested the code, but this really seems unfit.

### CODE REVIEW

**Comment by manusa** [comment]
Apparently this is also present in the upstream project 😳 

https://github.com/DP-3T/dp3t-sdk-backend/blob/2efe45c7affd580b5fd443403771dd0e3065577a/dpppt-backend-sdk/dpppt-backend-sdk-ws/src/main/java/org/dpppt/backend/sdk/ws/security/JWTValidator.java#L35

**Comment by iCesofT** [comment]
Hi manusa,

why do you recommend to delete that code? It is used for "testing" (if the token contains that claim) and also it is from "DP^3T repository".

Regards

**Comment by manusa** [comment]
Hi @iCesofT 

As I said I haven't had the chance to try out the project(s) yet 😓 . I got hold of this _"issue"_  in a discussion group and was quite surprised no one else had opened a PR yet.

From your words, I understand you are using this claim to bypass additional validations for a token that's forged specifically for testing purposes.

It still appears to be dangerous (IMHO). If these tests aren't performed in a production environment, it would certainly be better to have a specific `JWTValidator` bean for testing environments.

Anyway, I'm really happy to see there's some activity in these repos and that the project was finally open-sourced. Let's see if we can build some community around them.

**Comment by iCesofT** [comment]
The code comes from DP^3T and it is used for testing proposal.

**Pull request closed without merging**
